### PR TITLE
Memory usage fix

### PR DESCRIPTION
**Pull request by Xh4H**
Setting this system flag to 0 makes all the processes created to spawn with `:fullsweep_after = 0` which makes the GC to come in to clean data as soon as possible.

I have been monitoring Coxir with this change and the memory used by processes has lowered around 35% (from 180-190MBs to 100MBs *and from time to time it stays at 70MBs*).

I am still investigating a proper way to improve the memory usage but this can work as a temporary fix.

### CODE REVIEW

**Comment by satom99** [comment]
I don't think we want this. As you mention, we'd affect **all** of the processes created within the system and this is clearly not ideal at all.

Wouldn't a `spawn_opt` on the problematic processes suffice?

**Comment by Xh4H** [comment]
I commented in DAPI channel all my progress, included that, using spawn_opt. We saw that it lowered the memory usage the same way ``fullsweep_after = 0`` has, but instead, it increased slowly and steadily the memory used by binaries.

**Comment by Xh4H** [comment]
04d9f59 brings a huge memory improvement. After 10 minutes, the memory used by coxir in a bot in a few guilds + Discord API (a very big server) sits in 100 MBs 
image

**Comment by Xh4H** [comment]
Update: after running the bot for 42 minutes, the memory is still great.
image

**Comment by Xh4H** [comment]
Second update: I have tested creating a single Middle instead of the number of schedulers online. (1 vs 4)

Result: 
· [1 Middle](https://cdn.discordapp.com/attachments/432535429162729494/489787169796259850/unknown.png) -> 41 MB
· [4 Middles](https://i.imgur.com/FOmCXDi.png) -> 148MB

**Comment by satom99** [comment]
I don't quite like the idea of keeping the number of `Middle` processes down to one - however I do see why we want this. I am thinking that perhaps a configurable value to set the amount of processes to start could be a nice thing to have? Either this or we could instruct or specify somewhere in the docs in a _Large-bots-specific_ section how to properly add the forementioned processes to the library's internal supervision tree - i.e. through a `Supervisor.start_child/?` call.

Aside from this, I don't think hibernating the consumer process is a good idea either. And the same goes for keeping the buffer size at that fix amount of bytes. :thinking:

**Comment by Xh4H** [comment]
We can easily make the number of Middles configurable by the user by making him set certain variable in the config file.

I tested two different versions of the library, one with hibernating on, and the other one off, and the results were clear. Hibernating reduces the amount of memory, and as I saw, it did not affect performance at all.
[From a 123MB of memory with hibernation on to 206MB with hibernation off](https://media.discordapp.net/attachments/469034950679592960/490132911128051713/unknown.png?width=942&height=464) *left window is the observer of the library version with hibernation off*.

About the fixed amount of bytes we can inspect to see which values suits you better, but nevertheless we do need to set one since producer_consumers aka Middles have by default `buffer_size` set to infinity.

**Comment by Xh4H** [comment]
image !!

**Pull request closed without merging**
