### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by Xh4H**
Added 3 examples:
· Welcome
· Reply
· Embedded messages

More will come.

### CODE REVIEW

**Comment by satom99** [comment]
I would consider moving this into a separate repo. Thoughts?

**Comment by Xh4H** [comment]
Considering it is something strictly related to the lib, and taking into account how other big libs structure themselves, I would maintain as is, which is, everything in a folder called Examples

**Comment by satom99** [comment]
In that case; how about we have a different consumer per functionality?
Currently there are 3 projects whose only difference is the consumer.

**Comment by Xh4H** [comment]
In my opinion, for beginners it is super helpful to have working examples with the build and folder/files structures.

Apart from this, in the next updates I am thinking on integrating your commander, so I would suggest keeping everything as is.

**Pull request closed without merging**
